Added spring jpa data & postgresql data source

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,25 +1,25 @@
 #!/bin/sh
+# Standard POSIX sh pre-commit hook
 
-echo "runing pre-commite hook"
+echo "Running pre-commit hook..."
+
+# Run Spotless check
 ./mvnw spotless:check
-
-if [$? -ne 0]; then
-echo "spotless check failed, aborting"
-exit 1
-
+# Check the exit code of the last command
+if [ $? -ne 0 ]; then
+    echo "Spotless check failed. Aborting commit."
+    exit 1
 fi
 
-echo "spotless:check done"
-echo "runing mvn-test"
+echo "Spotless check passed. Running tests..."
 
+# Run tests
 ./mvnw test
-
-if [$? -ne 0]; then
-echo "test failed, aborting"
-exit 1
-
+# Check the exit code of the last command
+if [ $? -ne 0 ]; then
+    echo "Tests failed. Aborting commit."
+    exit 1
 fi
 
-echo " pre-commit hook check and test done commiting .... "
-
+echo "Pre-commit checks passed. Proceeding with commit."
 exit 0
